#version 460
#extension GL_EXT_ray_query : require
#extension GL_GOOGLE_include_directive : require
#define COMPUTE_PASS
#define SURFACE_PASS
#define RTXDI_PASS
#include "common.glsl"
#include "Rtxdi/DI/SpatialResampling.hlsli"
layout(local_size_x=8,local_size_y=8) in;
void main() {
    ivec2 p=ivec2(gl_GlobalInvocationID.xy);
    if (!inBounds(p)) return;
    RAB_Surface s=RAB_GetGBufferSurface(p,false);
    RTXDI_ReservoirBufferParameters buffers=diBufferParams();
    RTXDI_DIReservoir r=RTXDI_EmptyDIReservoir();
    if (RAB_IsSurfaceValid(s)) {
        RTXDI_DIReservoir center=RTXDI_LoadDIReservoir(buffers,uvec2(p),1);
        RTXDI_RandomSamplerState randomState=RTXDI_InitRandomSampler(uvec2(p),g.counts.z,3);
        RTXDI_DISpatialResamplingParameters params;
        params.numSamples=4;
        params.numDisocclusionBoostSamples=8;
        params.samplingRadius=16;
        params.biasCorrectionMode=RTXDI_BIAS_CORRECTION_RAY_TRACED;
        params.depthThreshold=.01;
        params.normalThreshold=.95;
        params.targetHistoryLength=8;
        params.enableMaterialSimilarityTest=true;
        params.discountNaiveSamples=false;
        params.pad1=params.pad2=params.pad3=0;
        RAB_LightSample selected=RAB_EmptyLightSample();
        r=RTXDI_DISpatialResampling(uvec2(p),s,center,randomState,diRuntimeParams(),buffers,1,params,selected);
    }
    RTXDI_StoreDIReservoir(r,buffers,uvec2(p),2);
}
